//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCrawler.HtmlProcessor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCrawler.HtmlProcessor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be the empty string..
        /// </summary>
        public static string Option_Option_Cannot_be_the_empty_string_ {
            get {
                return ResourceManager.GetString("Option_Option_Cannot_be_the_empty_string_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot provide maxValueCount of 0 for OptionValueType.Required or OptionValueType.Optional..
        /// </summary>
        public static string Option_Option_Cannot_provide_maxValueCount_of_0_for_OptionValueType_Required_or_OptionValueType_Optional_ {
            get {
                return ResourceManager.GetString("Option_Option_Cannot_provide_maxValueCount_of_0_for_OptionValueType_Required_or_O" +
                        "ptionValueType_Optional_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default option handler &apos;&lt;&gt;&apos; cannot require values..
        /// </summary>
        public static string Option_Option_The_default_option_handler______cannot_require_values_ {
            get {
                return ResourceManager.GetString("Option_Option_The_default_option_handler______cannot_require_values_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty option names are not supported..
        /// </summary>
        public static string Option_ParsePrototype_Empty_option_names_are_not_supported_ {
            get {
                return ResourceManager.GetString("Option_ParsePrototype_Empty_option_names_are_not_supported_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OriginalReferrerUrl.
        /// </summary>
        public static string PropertyBagKeyOriginalReferrerUrl {
            get {
                return ResourceManager.GetString("PropertyBagKeyOriginalReferrerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OriginalUrl.
        /// </summary>
        public static string PropertyBagKeyOriginalUrl {
            get {
                return ResourceManager.GetString("PropertyBagKeyOriginalUrl", resourceCulture);
            }
        }
    }
}
